ABC_REPO: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction"
ABC_RESULTS: "results/abc_results/"
ABC_biosamples_table: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/config/config_biosamples_chr22.tsv"

E2G_FEATURES_REPO: "/oak/stanford/groups/engreitz/Users/atan5133/encode_e2g_features"
E2G_FEATURES_RESULTS: "results/e2g_features_results/"
